### ISSUE TITLE
How do i look at them

### ISSUE THREAD

**Issue by icanbarely** [miikart/befunnynowresponses#1]
I new to this

**Comment by miikart** [comment]
### click on the folders
or download fiddler and setup https request decrypt and launch befunny now 




#setups below
click on any requests from https://9b727.playfabapi.com
on 
the top click textview 
on the bottom also lclick textview
click on raw on the top to see the game requests w/ headers do the same on the bottom if you want to see the server headers that arent not the main thing 

![image](https://github.com/miikart/befunnynowresponses/assets/92797301/73fe9969-da0b-48bd-a63f-dc7d79850314)
